<project name="Echecs" basedir="." default="default">
    <target name="default" depends="CompileP1, CompileP2, RunP2">

    </target>
    <target name="CompileP1">
        <mkdir dir="Partie 1/class"/>
        <javac srcdir="Partie 1/jeu" destdir="Partie 1/class" includeantruntime="false"/>
    </target>

    <target name="CompileP2">
        <mkdir dir="Partie 2/class"/>
        <javac srcdir="Partie 2/jeu" destdir="Partie 2/class" includeantruntime="false">
            <classpath>
                <pathelement path="Partie 2/lib/gson-2.10.1.jar"/>
            </classpath>
        </javac>
    </target>

    <target name="RunP1">
        <java classname="jeu.Plateau" fork="true">
            <classpath>
                <pathelement location="Partie 1/class/"/>
            </classpath>
        </java>
    </target>

    <target name="RunP2">
        <java classname="jeu.Plateau" fork="true">
            <classpath>
                <pathelement location="Partie 2/class/"/>
                <pathelement path="Partie 2/lib/gson-2.10.1.jar"/>
            </classpath>
        </java>

    </target>

    <target name="testJSONParser">
        <java classname="jeu.JSON_parser" fork="true">
            <classpath>
                <pathelement location="Partie 2/class/"/>
                <pathelement path="Partie 2/lib/gson-2.10.1.jar"/>
            </classpath>
        </java>

    </target>

    <target name="jar">

        <jar destfile="Chess.jar">
            <manifest>
                <attribute name="Main-Class" value="jeu.Plateau"/>
            </manifest>

            <fileset dir="Partie 2/class/"/>

            <!-- Dépendance Gson -->
            <zipfileset src="Partie 2/lib/gson-2.10.1.jar"/>
        </jar>
    </target>

</project>