<project name="Echecs" basedir="." default="default">
    <target name="default" depends="Compile, Run">

    </target>
    <target name="Compile">
        <mkdir dir="class"/>
        <javac srcdir="jeu" destdir="class" includeantruntime="false"/>
    </target>


    <target name="Run">
        <java classname="fr.Plateau" fork="true">
            <classpath>
                <pathelement location="class/"/>
            </classpath>
        </java>
    </target>

    <target name="package" depends="Compile">
        <jar destfile="Chess.jar">
            <manifest>
                <attribute name="Main-Class" value="jeu.Plateau"/>
            </manifest>

            <fileset dir="class/"/>
        </jar>
    </target>

    <target name="clean">
        <delete dir="class"/>
    </target>
</project>