<project name="Echecs" basedir="." default="default">
    <target name="default" depends="Compile, Run">

    </target>

    <target name="Compile">
        <mkdir dir="class"/>
        <javac srcdir="jeu" destdir="class" includeantruntime="false">
            <classpath>
                <pathelement path="lib/gson-2.10.1.jar"/>
            </classpath>
        </javac>
    </target>


    <target name="Run">
        <java classname="jeu.Plateau" fork="true">
            <classpath>
                <pathelement location="class/"/>
                <pathelement path="lib/gson-2.10.1.jar"/>
            </classpath>
        </java>

    </target>

    <target name="jar" depends="Compile">

        <jar destfile="Chess.jar">
            <manifest>
                <attribute name="Main-Class" value="jeu.Plateau"/>
            </manifest>

            <fileset dir="class/"/>

            <!-- Dépendance Gson -->
            <zipfileset src="lib/gson-2.10.1.jar"/>
        </jar>
    </target>

    <target name="clean">
        <delete dir="class"/>
    </target>

</project>